import type { ViewConfig } from './index';
import { createViewConfig } from './schema';

/**
 * View configurations for the application routing system.
 * This is the single source of truth for all view definitions.
 *
 * Standardized schema:
 * - requiresAuth: boolean - whether the view requires authentication
 * - primary: boolean - whether this is a primary/main view
 * - defaultRoute: boolean - whether this is the default landing route
 *
 * Uses top-level properties with metadata preserved for backward compatibility.
 */
export const VIEW_CONFIGS: ViewConfig[] = [
  createViewConfig({
    id: 'practice',
    title: '练习',
    icon: 'practice',
    description: '核心练习界面，支持多种练习模式',
    category: 'learning',
    navigationOrder: 1,
    menuGroup: 'main',
    primary: true,
    defaultRoute: true,
    requiresAuth: false,
    adaptiveState: { difficulty: 'normal', priority: 10, flowStates: ['normal', 'focused'] },
    metadata: { primary: true, defaultRoute: true, requiresAuth: false },
  }),
  createViewConfig({
    id: 'progress',
    title: '学习进度',
    icon: 'progress',
    description: '查看学习进度和能力提升趋势',
    category: 'progress',
    navigationOrder: 10,
    menuGroup: 'progress',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'profile',
    title: '个人资料',
    icon: 'profile',
    description: '个人信息和学习设置',
    category: 'system',
    navigationOrder: 50,
    menuGroup: 'settings',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'efficiency',
    title: '学习效率',
    icon: 'efficiency',
    description: '分析学习效率和数据统计',
    category: 'progress',
    navigationOrder: 11,
    menuGroup: 'progress',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'mistake-book',
    title: '错题本',
    icon: 'mistake-book',
    description: '收录所有做错的题目，便于针对性复习',
    category: 'learning',
    navigationOrder: 3,
    menuGroup: 'review',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'history',
    title: '练习历史',
    icon: 'history',
    description: '查看历史练习记录',
    category: 'progress',
    navigationOrder: 12,
    menuGroup: 'progress',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'data',
    title: '数据管理',
    icon: 'data',
    description: '导入导出学习数据',
    category: 'system',
    navigationOrder: 60,
    menuGroup: 'settings',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'review',
    title: '智能复习',
    icon: 'review',
    description: '基于遗忘曲线智能安排复习计划',
    category: 'learning',
    navigationOrder: 4,
    menuGroup: 'review',
    requiresAuth: false,
    adaptiveState: { difficulty: 'easy', priority: 6, flowStates: ['normal', 'fatigued'] },
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'weakness',
    title: '弱点分析',
    icon: 'weakness',
    description: '分析薄弱知识点',
    category: 'progress',
    navigationOrder: 13,
    menuGroup: 'progress',
    requiresAuth: false,
    adaptiveState: { difficulty: 'hard', priority: 8, flowStates: ['focused'] },
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'challenges',
    title: '每日挑战',
    icon: 'challenges',
    description: '每日挑战任务，完成获得额外奖励',
    category: 'achievement',
    navigationOrder: 20,
    menuGroup: 'gamification',
    requiresAuth: false,
    adaptiveState: { difficulty: 'normal', priority: 7, flowStates: ['focused', 'normal'] },
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'badges',
    title: '成就徽章',
    icon: 'badges',
    description: '查看和炫耀学习成就',
    category: 'achievement',
    navigationOrder: 21,
    menuGroup: 'gamification',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'leaderboard',
    title: '排行榜',
    icon: 'leaderboard',
    description: '查看学习排行榜',
    category: 'social',
    navigationOrder: 30,
    menuGroup: 'social',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'invite',
    title: '邀请好友',
    icon: 'invite',
    description: '邀请好友一起学习',
    category: 'social',
    navigationOrder: 31,
    menuGroup: 'social',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'dictionary-browser',
    title: '词典浏览',
    icon: 'dictionary',
    description: '浏览词典中的所有单词',
    category: 'learning',
    navigationOrder: 5,
    menuGroup: 'learning',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'goals',
    title: '目标设置',
    icon: 'goals',
    description: '设置每日和每周学习目标',
    category: 'achievement',
    navigationOrder: 22,
    menuGroup: 'gamification',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'churn-dashboard',
    title: '流失预警',
    icon: 'churn',
    description: '用户流失风险预警仪表盘',
    category: 'system',
    navigationOrder: 70,
    menuGroup: 'admin',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'learn-insight',
    title: '学习洞察',
    icon: 'insight',
    description: '深度学习行为分析和洞察',
    category: 'progress',
    navigationOrder: 14,
    menuGroup: 'progress',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'learn-insight-dashboard',
    title: '学习仪表盘',
    icon: 'dashboard',
    description: '学习数据可视化仪表盘',
    category: 'progress',
    navigationOrder: 15,
    menuGroup: 'progress',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'learning-report',
    title: '学习报告',
    icon: 'report',
    description: '生成和分享学习报告',
    category: 'progress',
    navigationOrder: 16,
    menuGroup: 'progress',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
  createViewConfig({
    id: 'learn-profile',
    title: '学习画像',
    icon: 'user',
    description: '查看个人学习数据统计',
    category: 'progress',
    navigationOrder: 17,
    menuGroup: 'progress',
    requiresAuth: false,
    metadata: { requiresAuth: false },
  }),
];