export const wordLists: Record<string, string[]> = {
  // 初中词汇 — 基础高频词
  junior: [
    'ability', 'accept', 'accident', 'achieve', 'across', 'action', 'activity',
    'actually', 'add', 'address', 'admire', 'admit', 'adult', 'advance',
    'adventure', 'advise', 'afford', 'afraid', 'Africa', 'African', 'after',
    'afternoon', 'again', 'against', 'age', 'agency', 'agent', 'ago', 'agree',
    'agreement', 'ahead', 'aid', 'aim', 'air', 'aircraft', 'airline', 'airport',
    'alarm', 'alike', 'alive', 'allow', 'almost', 'alone', 'along', 'aloud',
    'already', 'also', 'although', 'altogether', 'always', 'amaze', 'ambition',
    'ambulance', 'America', 'American', 'among', 'amount', 'ancient', 'and',
    'anger', 'angle', 'angry', 'animal', 'announce', 'annoy', 'another',
    'answer', 'ant', 'anxiety', 'anxious', 'any', 'anybody', 'anyhow', 'anyone',
    'anything', 'anyway', 'anywhere', 'apart', 'apartment', 'apologize',
    'apparent', 'appeal', 'appear', 'appetite', 'applaud', 'apple', 'applicant',
    'application', 'apply', 'appoint', 'appointment', 'appreciate', 'approach',
    'appropriate', 'approval', 'approve', 'approximately', 'April', 'architect',
    'area', 'argue', 'argument', 'arise', 'arithmetic', 'arm', 'army', 'around',
    'arrange', 'arrangement', 'arrest', 'arrival', 'arrive', 'art', 'article',
    'artificial', 'artist', 'as', 'ash', 'ashamed', 'Asia', 'Asian', 'aside',
    'ask', 'asleep', 'aspect', 'assess', 'assessment', 'assist', 'assistance',
    'assistant', 'associate', 'association', 'assume', 'assumption', 'astonish',
    'astronaut', 'astronomer', 'at', 'athlete', 'athletic', 'Atlantic',
    'atmosphere', 'atom', 'attach', 'attack', 'attain', 'attempt', 'attend',
    'attention', 'attitude', 'attract', 'attraction', 'attractive', 'attribute',
    'audience', 'August', 'aunt', 'Australia', 'Australian', 'author',
    'authority', 'automatic', 'autumn', 'available', 'avenue', 'average',
    'avoid', 'awake', 'award', 'aware', 'away', 'awesome', 'awful', 'awkward',
  ],

  // 高中词汇 — 进阶核心词
  senior: [
    'abandon', 'abnormal', 'abolish', 'abortion', 'abrupt', 'absolute',
    'absorb', 'abstract', 'absurd', 'abundant', 'abuse', 'academic',
    'academy', 'accelerate', 'accent', 'access', 'accessible', 'accommodate',
    'accommodation', 'accompany', 'accomplish', 'accord', 'account',
    'accumulate', 'accuracy', 'accurate', 'accuse', 'accustomed', 'ache',
    'acid', 'acknowledge', 'acquaintance', 'acquire', 'acquisition', 'acre',
    'adapt', 'addicted', 'addition', 'adequate', 'adjust', 'administration',
    'admirable', 'admission', 'adolescent', 'adopt', 'adore', 'advancement',
    'advertise', 'advocate', 'aesthetic', 'affect', 'affection', 'affirm',
    'affluent', 'agenda', 'aggressive', 'agricultural', 'agriculture',
    'airmail', 'aisle', 'album', 'alcohol', 'alcoholic', 'alert', 'algebra',
    'allergic', 'allocate', 'allowance', 'ally', 'alphabet', 'alter',
    'alternative', 'altitude', 'aluminum', 'amateur', 'amaze', 'ambassador',
    'ambiguous', 'ambition', 'ample', 'amuse', 'analogy', 'analysis',
    'analyze', 'ancestor', 'anchor', 'anecdote', 'anniversary', 'antique',
    'anxiety', 'apparatus', 'appealing', 'appetite', 'applause', 'applicant',
    'application', 'applied', 'appreciate', 'apprentice', 'appropriate',
    'approve', 'arbitrary', 'archaeology', 'architecture', 'arithmetic',
    'arrange', 'array', 'arrow', 'articulate', 'artificial', 'ashamed',
    'aspect', 'aspiration', 'assemble', 'assembly', 'assert', 'assess',
    'assign', 'assist', 'associate', 'assume', 'assumption', 'assure',
    'astonish', 'astronomy', 'athlete', 'atmosphere', 'atom', 'attach',
    'attain', 'attempt', 'attend', 'attention', 'attitude', 'attract',
    'attribute', 'auction', 'audio', 'authentic', 'authority', 'automatic',
    'autonomy', 'available', 'avenue', 'average', 'aviation', 'avoid',
    'await', 'awaken', 'awareness', 'awkward',
  ],

  // CET-4 词汇 — 四级核心词
  cet4: [
    'abandon', 'ability', 'abnormal', 'aboard', 'abolish', 'abortion',
    'about', 'above', 'abroad', 'absence', 'absent', 'absolute', 'absorb',
    'abstract', 'absurd', 'abundant', 'abuse', 'academic', 'academy',
    'accelerate', 'accent', 'accept', 'acceptance', 'access', 'accessible',
    'accident', 'accidental', 'accommodate', 'accommodation', 'accompany',
    'accomplish', 'accord', 'accordance', 'according', 'accordingly',
    'account', 'accountant', 'accumulate', 'accuracy', 'accurate', 'accuse',
    'accustomed', 'ache', 'achieve', 'achievement', 'acid', 'acknowledge',
    'acquaintance', 'acquire', 'acquisition', 'acre', 'across', 'act',
    'action', 'active', 'activity', 'actor', 'actress', 'actual', 'actually',
    'acute', 'adapt', 'add', 'addicted', 'addition', 'additional', 'address',
    'adequate', 'adjust', 'administration', 'admire', 'admission', 'admit',
    'adolescent', 'adopt', 'adore', 'adult', 'advance', 'advanced',
    'advantage', 'adventure', 'adverb', 'advertise', 'advertisement',
    'advice', 'advise', 'advocate', 'affair', 'affect', 'affection',
    'afford', 'afraid', 'Africa', 'African', 'after', 'afternoon',
    'afterward', 'again', 'against', 'age', 'agency', 'agenda', 'agent',
    'aggressive', 'ago', 'agree', 'agreement', 'agricultural', 'agriculture',
    'ahead', 'aid', 'aim', 'air', 'aircraft', 'airline', 'airplane',
    'airport', 'alarm', 'alcohol', 'alcoholic', 'alert', 'alike', 'alive',
    'all', 'allow', 'allowance', 'almost', 'alone', 'along', 'alongside',
    'aloud', 'alphabet', 'already', 'also', 'alter', 'alternative',
    'although', 'altitude', 'altogether', 'aluminum', 'always', 'amaze',
    'ambassador', 'ambiguous', 'ambition', 'ambulance', 'America',
    'American', 'among', 'amount', 'ample', 'amuse', 'analysis', 'analyze',
    'ancestor', 'anchor', 'ancient', 'and', 'anecdote', 'anger', 'angle',
    'angry', 'animal', 'ankle', 'anniversary', 'announce', 'annoy',
    'annual', 'another', 'answer', 'ant', 'anticipate', 'antique',
    'anxiety', 'anxious', 'any', 'anybody', 'anyhow', 'anyone', 'anything',
    'anyway', 'anywhere', 'apart', 'apartment', 'apologize', 'apology',
    'apparent', 'appeal', 'appear', 'appearance', 'appetite', 'applaud',
    'applause', 'apple', 'appliance', 'applicable', 'applicant',
    'application', 'apply', 'appoint', 'appointment', 'appreciate',
    'approach', 'appropriate', 'approval', 'approve', 'approximately',
    'April', 'architect', 'architecture', 'area', 'argue', 'argument',
    'arise', 'arithmetic', 'arm', 'army', 'around', 'arrange',
    'arrangement', 'arrest', 'arrival', 'arrive', 'arrow', 'art', 'article',
    'articulate', 'artificial', 'artist', 'as', 'ash', 'ashamed', 'Asia',
    'Asian', 'aside', 'ask', 'asleep', 'aspect', 'aspiration', 'assemble',
    'assembly', 'assert', 'assess', 'assessment', 'assign', 'assist',
    'assistance', 'assistant', 'associate', 'association', 'assume',
    'assumption', 'assure', 'astonish', 'astronaut', 'astronomer',
    'astronomy', 'at', 'athlete', 'athletic', 'Atlantic', 'atmosphere',
    'atom', 'attach', 'attack', 'attain', 'attempt', 'attend', 'attention',
    'attitude', 'attract', 'attraction', 'attractive', 'attribute',
    'auction', 'audience', 'audio', 'August', 'aunt', 'Australia',
    'Australian', 'authentic', 'author', 'authority', 'automatic',
    'autonomy', 'autumn', 'available', 'avenue', 'average', 'aviation',
    'avoid', 'await', 'awaken', 'award', 'aware', 'awareness', 'away',
    'awesome', 'awful', 'awkward',
  ],

  // CET-6 词汇 — 六级核心词
  cet6: [
    'abbreviate', 'abdomen', 'abide', 'abnormal', 'abolish', 'abortion',
    'abrupt', 'absence', 'absent', 'absolute', 'absorb', 'abstract',
    'absurd', 'abundance', 'abundant', 'abuse', 'academic', 'academy',
    'accelerate', 'accent', 'acceptance', 'access', 'accessible',
    'accessory', 'accident', 'accidental', 'acclaim', 'accommodate',
    'accommodation', 'accompany', 'accomplish', 'accord', 'accordance',
    'accordingly', 'accountant', 'accumulate', 'accuracy', 'accurate',
    'accuse', 'accustomed', 'acknowledge', 'acquaint', 'acquaintance',
    'acquire', 'acquisition', 'activate', 'acute', 'adapt', 'addict',
    'addicted', 'adequate', 'adhere', 'adjacent', 'adjoin', 'administer',
    'administration', 'admiral', 'admiration', 'admission', 'adolescent',
    'adopt', 'adore', 'adorn', 'advance', 'advantageous', 'advent',
    'adverse', 'advertise', 'advocate', 'aerial', 'aesthetic', 'affiliate',
    'affirm', 'afflict', 'affluent', 'affordable', 'agenda', 'aggravate',
    'aggregate', 'aggressive', 'agony', 'agreeable', 'air-conditioning',
    'aisle', 'album', 'alert', 'algebra', 'alien', 'alienate', 'align',
    'alike', 'allege', 'allegiance', 'allergic', 'alleviate', 'alliance',
    'allocate', 'allowance', 'ally', 'alongside', 'alphabet', 'alter',
    'alternate', 'alternative', 'altitude', 'aluminum', 'amateur', 'amaze',
    'ambassador', 'ambiguous', 'ambition', 'ambulance', 'amend', 'ample',
    'amplify', 'amuse', 'analogy', 'analysis', 'analytical', 'analyze',
    'ancestor', 'anchor', 'anecdote', 'angel', 'anniversary', 'announce',
    'annoy', 'annual', 'anonymous', 'antique', 'anxiety', 'apologize',
    'apparatus', 'apparent', 'appealing', 'appetite', 'applaud', 'applause',
    'appliance', 'applicable', 'applicant', 'application', 'apply',
    'appoint', 'appreciate', 'apprentice', 'approach', 'appropriate',
    'approve', 'approximate', 'apt', 'arbitrary', 'archaeology',
    'architecture', 'arena', 'argue', 'arise', 'arithmetic', 'armor',
    'array', 'arrogant', 'arrow', 'articulate', 'artillery', 'artificial',
    'ascend', 'ascertain', 'ashamed', 'aspect', 'aspiration', 'aspire',
    'assassination', 'assault', 'assemble', 'assembly', 'assert', 'assess',
    'asset', 'assign', 'assignment', 'assimilate', 'assist', 'associate',
    'association', 'assume', 'assumption', 'assurance', 'assure',
    'astonish', 'astronomy', 'asylum', 'athlete', 'atlas', 'atmosphere',
    'atom', 'atomic', 'attach', 'attain', 'attendance', 'attendant',
    'attention', 'attic', 'attitude', 'attorney', 'attract', 'attraction',
    'attractive', 'attribute', 'auction', 'audience', 'audio', 'audit',
    'auditorium', 'augment', 'authentic', 'author', 'authoritative',
    'authority', 'authorize', 'automatic', 'autonomy', 'auxiliary',
    'available', 'avenue', 'average', 'aviation', 'avoid', 'await',
    'awaken', 'aware', 'awareness', 'awe', 'awful', 'awkward',
  ],

  // 雅思词汇 — 学术/移民高频词
  ielts: [
    'abandon', 'abide', 'abnormal', 'abolish', 'abortion', 'abrupt',
    'absence', 'absent', 'absolute', 'absorb', 'abstract', 'absurd',
    'abundance', 'abundant', 'abuse', 'academic', 'academy', 'accelerate',
    'accent', 'accept', 'acceptance', 'access', 'accessible', 'accessory',
    'accident', 'accidental', 'acclaim', 'accommodate', 'accommodation',
    'accompany', 'accomplish', 'accord', 'accordance', 'accordingly',
    'account', 'accountant', 'accumulate', 'accuracy', 'accurate', 'accuse',
    'accustomed', 'ache', 'achieve', 'achievement', 'acid', 'acknowledge',
    'acquaint', 'acquaintance', 'acquire', 'acquisition', 'acre', 'across',
    'activate', 'acute', 'adapt', 'addict', 'addicted', 'addition',
    'additional', 'address', 'adequate', 'adhere', 'adjacent', 'adjoin',
    'administer', 'administration', 'admiral', 'admiration', 'admire',
    'admission', 'admit', 'adolescent', 'adopt', 'adore', 'adorn',
    'advance', 'advanced', 'advantage', 'advantageous', 'adventure',
    'advent', 'adverse', 'advertise', 'advertisement', 'advice', 'advise',
    'advocate', 'affair', 'affect', 'affection', 'affiliate', 'affirm',
    'afflict', 'affluent', 'afford', 'affordable', 'afraid', 'Africa',
    'African', 'after', 'afternoon', 'afterward', 'again', 'against',
    'age', 'agency', 'agenda', 'agent', 'aggravate', 'aggregate',
    'aggressive', 'agony', 'ago', 'agree', 'agreeable', 'agreement',
    'agricultural', 'agriculture', 'ahead', 'aid', 'aim', 'air',
    'aircraft', 'airline', 'airplane', 'airport', 'aisle', 'alarm',
    'album', 'alcohol', 'alcoholic', 'alert', 'algebra', 'alien',
    'alienate', 'align', 'alike', 'alive', 'allege', 'allegiance',
    'allergic', 'alleviate', 'alliance', 'allocate', 'allow', 'allowance',
    'almost', 'alone', 'along', 'alongside', 'aloud', 'alphabet', 'alter',
    'alternate', 'alternative', 'although', 'altitude', 'altogether',
    'aluminum', 'always', 'amaze', 'ambassador', 'ambiguous', 'ambition',
    'ambulance', 'amend', 'America', 'American', 'among', 'amount',
    'ample', 'amuse', 'analysis', 'analytical', 'analyze', 'ancestor',
    'anchor', 'ancient', 'and', 'anecdote', 'angel', 'anger', 'angle',
    'angry', 'animal', 'ankle', 'anniversary', 'announce', 'annoy',
    'annual', 'anonymous', 'another', 'answer', 'ant', 'anticipate',
    'antique', 'anxiety', 'anxious', 'any', 'anybody', 'anyhow', 'anyone',
    'anything', 'anyway', 'anywhere', 'apart', 'apartment', 'apologize',
    'apology', 'apparatus', 'apparent', 'appeal', 'appear', 'appearance',
    'appealing', 'appetite', 'applaud', 'applause', 'apple', 'appliance',
    'applicable', 'applicant', 'application', 'apply', 'appoint',
    'appointment', 'appreciate', 'approach', 'appropriate', 'approval',
    'approve', 'approximate', 'approximately', 'April', 'apt', 'architect',
    'architecture', 'area', 'arena', 'argue', 'argument', 'arise',
    'arithmetic', 'arm', 'armor', 'army', 'around', 'arrange',
    'arrangement', 'array', 'arrest', 'arrival', 'arrive', 'arrow',
    'arrogant', 'art', 'article', 'articulate', 'artificial', 'artist',
    'as', 'ash', 'ashamed', 'Asia', 'Asian', 'aside', 'ask', 'asleep',
    'aspect', 'aspiration', 'aspire', 'assassination', 'assault',
    'assemble', 'assembly', 'assert', 'assess', 'assessment', 'asset',
    'assign', 'assignment', 'assist', 'assistance', 'assistant',
    'associate', 'association', 'assume', 'assumption', 'assurance',
    'assure', 'astonish', 'astronaut', 'astronomer', 'astronomy',
    'asylum', 'at', 'athlete', 'athletic', 'Atlantic', 'atlas',
    'atmosphere', 'atom', 'atomic', 'attach', 'attack', 'attain',
    'attempt', 'attend', 'attendance', 'attendant', 'attention', 'attic',
    'attitude', 'attorney', 'attract', 'attraction', 'attractive',
    'attribute', 'auction', 'audience', 'audio', 'audit', 'auditorium',
    'August', 'aunt', 'Australia', 'Australian', 'authentic', 'author',
    'authoritative', 'authority', 'authorize', 'automatic', 'autonomy',
    'autumn', 'auxiliary', 'available', 'avenue', 'average', 'aviation',
    'avoid', 'await', 'awaken', 'award', 'aware', 'awareness', 'away',
    'awe', 'awesome', 'awful', 'awkward',
  ],

  // 托福词汇 — 学术英语核心词
  toefl: [
    'abandon', 'abate', 'abbreviate', 'abdomen', 'abide', 'abnormal',
    'abolish', 'abortion', 'abound', 'abrupt', 'absence', 'absent',
    'absolute', 'absorb', 'abstract', 'absurd', 'abundance', 'abundant',
    'abuse', 'academic', 'academy', 'accelerate', 'accent', 'accept',
    'acceptance', 'access', 'accessible', 'accessory', 'accident',
    'accidental', 'acclaim', 'accommodate', 'accommodation', 'accompany',
    'accomplish', 'accord', 'accordance', 'accordingly', 'account',
    'accountant', 'accumulate', 'accuracy', 'accurate', 'accuse',
    'accustomed', 'ache', 'achieve', 'achievement', 'acid', 'acknowledge',
    'acoustic', 'acquaint', 'acquaintance', 'acquire', 'acquisition',
    'acre', 'across', 'activate', 'acute', 'adapt', 'addict', 'addicted',
    'addition', 'additional', 'address', 'adequate', 'adhere', 'adjacent',
    'adjoin', 'administer', 'administration', 'admiral', 'admiration',
    'admire', 'admission', 'admit', 'adolescent', 'adopt', 'adore',
    'adorn', 'advance', 'advanced', 'advantage', 'advantageous',
    'adventure', 'advent', 'adverse', 'advertise', 'advertisement',
    'advice', 'advise', 'advocate', 'aerial', 'aesthetic', 'affair',
    'affect', 'affection', 'affiliate', 'affirm', 'afflict', 'affluent',
    'afford', 'affordable', 'afraid', 'Africa', 'African', 'after',
    'afternoon', 'afterward', 'again', 'against', 'age', 'agency',
    'agenda', 'agent', 'aggravate', 'aggregate', 'aggressive', 'agony',
    'ago', 'agree', 'agreeable', 'agreement', 'agricultural', 'agriculture',
    'ahead', 'aid', 'aim', 'air', 'aircraft', 'airline', 'airplane',
    'airport', 'aisle', 'alarm', 'album', 'alcohol', 'alcoholic', 'alert',
    'algebra', 'alien', 'alienate', 'align', 'alike', 'alive', 'allege',
    'allegiance', 'allergic', 'alleviate', 'alliance', 'allocate',
    'allow', 'allowance', 'almost', 'alone', 'along', 'alongside',
    'aloud', 'alphabet', 'alter', 'alternate', 'alternative', 'although',
    'altitude', 'altogether', 'aluminum', 'always', 'amaze', 'ambassador',
    'ambiguous', 'ambition', 'ambulance', 'amend', 'America', 'American',
    'among', 'amount', 'ample', 'amplify', 'amuse', 'analogy', 'analysis',
    'analytical', 'analyze', 'ancestor', 'anchor', 'ancient', 'and',
    'anecdote', 'angel', 'anger', 'angle', 'angry', 'animal', 'ankle',
    'anniversary', 'announce', 'annoy', 'annual', 'anonymous', 'another',
    'answer', 'ant', 'anticipate', 'antique', 'anxiety', 'anxious',
    'any', 'anybody', 'anyhow', 'anyone', 'anything', 'anyway',
    'anywhere', 'apart', 'apartment', 'apologize', 'apology',
    'apparatus', 'apparent', 'appeal', 'appear', 'appearance',
    'appealing', 'appetite', 'applaud', 'applause', 'apple', 'appliance',
    'applicable', 'applicant', 'application', 'apply', 'appoint',
    'appointment', 'appreciate', 'approach', 'appropriate', 'approval',
    'approve', 'approximate', 'approximately', 'April', 'apt',
    'archaeology', 'architect', 'architecture', 'area', 'arena',
    'argue', 'argument', 'arise', 'arithmetic', 'arm', 'armor', 'army',
    'around', 'arrange', 'arrangement', 'array', 'arrest', 'arrival',
    'arrive', 'arrow', 'arrogant', 'art', 'article', 'articulate',
    'artillery', 'artificial', 'artist', 'as', 'ash', 'ashamed',
    'Asia', 'Asian', 'aside', 'ask', 'asleep', 'aspect', 'aspiration',
    'aspire', 'assassination', 'assault', 'assemble', 'assembly',
    'assert', 'assess', 'assessment', 'asset', 'assign', 'assignment',
    'assimilate', 'assist', 'assistance', 'assistant', 'associate',
    'association', 'assume', 'assumption', 'assurance', 'assure',
    'astonish', 'astronaut', 'astronomer', 'astronomy', 'asylum',
    'at', 'athlete', 'athletic', 'Atlantic', 'atlas', 'atmosphere',
    'atom', 'atomic', 'attach', 'attack', 'attain', 'attempt',
    'attend', 'attendance', 'attendant', 'attention', 'attic',
    'attitude', 'attorney', 'attract', 'attraction', 'attractive',
    'attribute', 'auction', 'audience', 'audio', 'audit', 'auditorium',
    'augment', 'August', 'aunt', 'Australia', 'Australian', 'authentic',
    'author', 'authoritative', 'authority', 'authorize', 'automatic',
    'autonomy', 'autumn', 'auxiliary', 'available', 'avenue', 'average',
    'aviation', 'avoid', 'await', 'awaken', 'award', 'aware', 'awareness',
    'away', 'awe', 'awesome', 'awful', 'awkward',
  ],

  // GRE 词汇 — 研究生入学考试高难度词
  gre: [
    'abacus', 'abandon', 'abate', 'abbreviate', 'abdicate', 'abdomen',
    'abduct', 'aberrant', 'aberration', 'abet', 'abeyance', 'abhor',
    'abhorrent', 'abide', 'abject', 'abjure', 'ablation', 'ablaze',
    'able', 'abnormal', 'aboard', 'abolish', 'abolition', 'abominable',
    'abominate', 'aboriginal', 'abort', 'abortion', 'abound', 'about',
    'above', 'aboveboard', 'abracadabra', 'abrade', 'abrasion',
    'abrasive', 'abreast', 'abridge', 'abridgment', 'abroad', 'abrogate',
    'abrupt', 'abscess', 'abscond', 'absence', 'absent', 'absentee',
    'absenteeism', 'absolute', 'absolution', 'absolutism', 'absolve',
    'absorb', 'absorbing', 'absorption', 'abstain', 'abstemious',
    'abstention', 'abstinence', 'abstract', 'abstraction', 'abstruse',
    'absurd', 'absurdity', 'abundance', 'abundant', 'abuse', 'abusive',
    'abut', 'abysmal', 'abyss', 'academic', 'academy', 'accede',
    'accelerate', 'acceleration', 'accelerator', 'accent', 'accentuate',
    'accept', 'acceptability', 'acceptable', 'acceptance', 'access',
    'accessible', 'accession', 'accessory', 'accident', 'accidental',
    'acclaim', 'acclimate', 'acclivity', 'accolade', 'accommodate',
    'accommodation', 'accompaniment', 'accompany', 'accomplice',
    'accomplish', 'accomplished', 'accomplishment', 'accord', 'accordance',
    'according', 'accordingly', 'accordion', 'accost', 'account',
    'accountability', 'accountable', 'accountancy', 'accountant',
    'accouter', 'accredit', 'accretion', 'accrue', 'accumulate',
    'accumulation', 'accuracy', 'accurate', 'accursed', 'accusation',
    'accuse', 'accustom', 'accustomed', 'ace', 'acerbic', 'acerbity',
    'acetate', 'acetic', 'ache', 'achieve', 'achievement', 'achromatic',
    'acid', 'acidic', 'acidulous', 'acknowledge', 'acknowledgment',
    'acme', 'acne', 'acolyte', 'acorn', 'acoustic', 'acoustics',
    'acquaint', 'acquaintance', 'acquiesce', 'acquiescence', 'acquire',
    'acquired', 'acquisition', 'acquisitive', 'acquit', 'acquittal',
    'acre', 'acreage', 'acrid', 'acrimonious', 'acrimony', 'acrobat',
    'acrobatic', 'acronym', 'acropolis', 'across', 'acrylic', 'act',
    'acting', 'action', 'activate', 'active', 'activism', 'activist',
    'activity', 'actor', 'actress', 'actual', 'actuality', 'actually',
    'actuate', 'acuity', 'acumen', 'acute', 'adage', 'adagio', 'adamant',
    'adapt', 'adaptable', 'adaptation', 'adapter', 'add', 'addendum',
    'adder', 'addict', 'addicted', 'addiction', 'addition', 'additional',
    'additive', 'addle', 'address', 'addressee', 'adduce', 'adenoids',
    'adept', 'adequacy', 'adequate', 'adhere', 'adherence', 'adherent',
    'adhesion', 'adhesive', 'adieu', 'adjacent', 'adjective', 'adjoin',
    'adjoining', 'adjourn', 'adjournment', 'adjudge', 'adjudicate',
    'adjunct', 'adjust', 'adjustment', 'adjutant', 'ad-lib', 'administer',
    'administration', 'administrative', 'administrator', 'admirable',
    'admiral', 'admiralty', 'admiration', 'admire', 'admissible',
    'admission', 'admit', 'admittance', 'admittedly', 'admixture',
    'admonish', 'admonition', 'ado', 'adobe', 'adolescence', 'adolescent',
    'adopt', 'adopted', 'adoption', 'adorable', 'adore', 'adorn',
    'adornment', 'adrenaline', 'adrift', 'adroit', 'adsorb', 'adulate',
    'adulation', 'adult', 'adulterate', 'adulteration', 'adultery',
    'advance', 'advanced', 'advancement', 'advantage', 'advantageous',
    'advent', 'adventure', 'adventurer', 'adventuresome', 'adventurous',
    'adverb', 'adverbial', 'adversary', 'adverse', 'adversity',
    'advertise', 'advertisement', 'advertising', 'advice', 'advisable',
    'advise', 'advisedly', 'adviser', 'advisory', 'advocacy', 'advocate',
    'aegis', 'aerate', 'aerial', 'aerie', 'aerobatics', 'aerobics',
    'aerodynamics', 'aeronautics', 'aerosol', 'aerospace', 'aesthetic',
    'aesthetics', 'affable', 'affair', 'affect', 'affectation',
    'affected', 'affecting', 'affection', 'affectionate', 'affidavit',
    'affiliate', 'affiliation', 'affinity', 'affirm', 'affirmation',
    'affirmative', 'affix', 'afflict', 'affliction', 'affluence',
    'affluent', 'afford', 'affordable', 'afforest', 'affray', 'affront',
    'aficionado', 'afield', 'afire', 'aflame', 'afloat', 'afoot',
    'aforementioned', 'aforesaid', 'afraid', 'afresh', 'Africa',
    'African', 'after', 'aftereffect', 'afterlife', 'aftermath',
    'afternoon', 'aftershave', 'afterthought', 'afterward', 'again',
    'against', 'agape', 'age', 'aged', 'agency', 'agenda', 'agent',
    'agglomerate', 'aggrandize', 'aggravate', 'aggravation', 'aggregate',
    'aggregation', 'aggression', 'aggressive', 'aggressor', 'aggrieve',
    'aghast', 'agile', 'agility', 'aging', 'agitate', 'agitation',
    'agitator', 'agleam', 'agnostic', 'ago', 'agog', 'agonize', 'agony',
    'agree', 'agreeable', 'agreement', 'agricultural', 'agriculture',
    'agronomist', 'agronomy', 'aground', 'ahead', 'aid', 'aide',
    'ail', 'ailment', 'aim', 'air', 'airborne', 'aircraft', 'airfield',
    'airforce', 'airily', 'airing', 'airless', 'airlift', 'airline',
    'airliner', 'airmail', 'airman', 'airplane', 'airport', 'airship',
    'airsick', 'airspace', 'airstrip', 'airtight', 'airway', 'airy',
    'aisle', 'ajar', 'akin', 'alarm', 'alarming', 'alarmist', 'alas',
    'albino', 'album', 'albumen', 'alchemy', 'alcohol', 'alcoholic',
    'alcoholism', 'alcove', 'alder', 'alderman', 'ale', 'alert',
    'alfalfa', 'alga', 'algebra', 'alias', 'alibi', 'alien', 'alienate',
    'alienation', 'alight', 'align', 'alignment', 'alike', 'alimentary',
    'alive', 'alkali', 'alkaline', 'all', 'allay', 'allege', 'alleged',
    'allegiance', 'allegorical', 'allegory', 'allergic', 'allergy',
    'alleviate', 'alleviation', 'alley', 'alliance', 'allied', 'alligator',
    'allocate', 'allocation', 'allot', 'allotment', 'allow', 'allowance',
    'alloy', 'allude', 'allure', 'allurement', 'allusion', 'alluvial',
    'ally', 'almanac', 'almighty', 'almond', 'almost', 'alms', 'almshouse',
    'aloe', 'aloft', 'alone', 'along', 'alongside', 'aloof', 'aloud',
    'alphabet', 'alphabetical', 'alpine', 'already', 'also', 'altar',
    'alter', 'alteration', 'altercation', 'alternate', 'alternative',
    'although', 'altitude', 'alto', 'altogether', 'altruism', 'altruist',
    'aluminum', 'alumna', 'alumni', 'always', 'amalgam', 'amalgamate',
    'amass', 'amateur', 'amateurish', 'amaze', 'amazement', 'amazing',
    'ambassador', 'amber', 'ambiance', 'ambidextrous', 'ambient',
    'ambiguous', 'ambition', 'ambitious', 'ambivalent', 'amble',
    'ambulance', 'ambush', 'ameliorate', 'amenable', 'amend', 'amendment',
    'amenity', 'America', 'American', 'amethyst', 'amiable', 'amicable',
    'amid', 'amidships', 'amiss', 'amity', 'ammeter', 'ammunition',
    'amnesia', 'amnesty', 'amoeba', 'amok', 'among', 'amoral', 'amorous',
    'amount', 'ampere', 'amphetamine', 'amphibian', 'amphibious',
    'amphitheater', 'ample', 'amplification', 'amplifier', 'amplify',
    'amplitude', 'amply', 'amputate', 'amputation', 'amputee', 'amuse',
    'amusement', 'amusing', 'anachronism', 'anachronistic', 'anaconda',
    'anaemia', 'anaemic', 'anaesthesia', 'anaesthetic', 'anagram',
    'anal', 'analgesia', 'analgesic', 'analogous', 'analogue', 'analogy',
    'analysis', 'analyst', 'analytic', 'analytical', 'analyze',
    'anarchic', 'anarchism', 'anarchist', 'anarchy', 'anathema',
    'anatomical', 'anatomy', 'ancestor', 'ancestral', 'ancestry',
    'anchor', 'anchorage', 'anchovy', 'ancient', 'and', 'anecdotal',
    'anecdote', 'anemia', 'anemic', 'anemone', 'anesthesia', 'anew',
    'angel', 'angelic', 'anger', 'angle', 'angler', 'anglicize',
    'angrily', 'angry', 'angst', 'anguish', 'angular', 'animal',
    'animate', 'animated', 'animation', 'animosity', 'ankle', 'annals',
    'annex', 'annexation', 'annihilate', 'annihilation', 'anniversary',
    'annotate', 'annotation', 'announce', 'announcement', 'announcer',
    'annoy', 'annoyance', 'annual', 'annuity', 'annul', 'annulment',
    'anode', 'anoint', 'anomalous', 'anomaly', 'anon', 'anonymity',
    'anonymous', 'anorak', 'another', 'answer', 'answerable', 'ant',
    'antagonism', 'antagonist', 'antagonistic', 'antagonize', 'antarctic',
    'ante', 'antecedent', 'antechamber', 'antedate', 'antelope',
    'antenna', 'anterior', 'anthem', 'anthology', 'anthracite',
    'anthropoid', 'anthropologist', 'anthropology', 'antibiotic',
    'antibody', 'antic', 'anticipate', 'anticipation', 'anticlimax',
    'antics', 'antidote', 'antifreeze', 'antihistamine', 'antipathy',
    'antiquarian', 'antiquated', 'antique', 'antiquity', 'antiseptic',
    'antisocial', 'antithesis', 'antler', 'antonym', 'anus', 'anvil',
    'anxiety', 'anxious', 'any', 'anybody', 'anyhow', 'anyone',
    'anything', 'anyway', 'anywhere', 'aorta', 'apace', 'apart',
    'apartheid', 'apartment', 'apathetic', 'apathy', 'ape', 'aperitif',
    'aperture', 'apex', 'aphid', 'aphorism', 'aphrodisiac', 'apiece',
    'aplomb', 'apocalypse', 'apocalyptic', 'apocryphal', 'apologetic',
    'apologize', 'apology', 'apoplectic', 'apoplexy', 'apostasy',
    'apostate', 'apostle', 'apostrophe', 'apothecary', 'apotheosis',
    'appall', 'appalling', 'apparatus', 'apparel', 'apparent',
    'apparently', 'apparition', 'appeal', 'appealing', 'appear',
    'appearance', 'appease', 'appeasement', 'appellate', 'append',
    'appendage', 'appendicitis', 'appendix', 'appetite', 'appetizer',
    'appetizing', 'applaud', 'applause', 'apple', 'appliance',
    'applicable', 'applicant', 'application', 'applied', 'apply',
    'appoint', 'appointee', 'appointment', 'apportion', 'apposite',
    'appraisal', 'appraise', 'appreciable', 'appreciate', 'appreciation',
    'appreciative', 'apprehend', 'apprehension', 'apprehensive',
    'apprentice', 'apprise', 'approach', 'approachable', 'approbation',
    'appropriate', 'appropriation', 'approval', 'approve', 'approximate',
    'approximately', 'approximation', 'apricot', 'April', 'apron',
    'apropos', 'apt', 'aptitude', 'aquamarine', 'aquarium', 'aquatic',
    'aqueduct', 'aqueous', 'aquiline', 'Arab', 'Arabic', 'arable',
    'arbiter', 'arbitrary', 'arbitrate', 'arbitration', 'arbitrator',
    'arbor', 'arboreal', 'arc', 'arcade', 'arch', 'archaeological',
    'archaeologist', 'archaeology', 'archaic', 'archaism', 'archangel',
    'archbishop', 'archer', 'archetype', 'archipelago', 'architect',
    'architectural', 'architecture', 'archive', 'archivist', 'arctic',
    'ardent', 'ardor', 'arduous', 'are', 'area', 'arena', 'argue',
    'argument', 'argumentative', 'aria', 'arid', 'arise', 'aristocracy',
    'aristocrat', 'aristocratic', 'arithmetic', 'ark', 'arm', 'armada',
    'armament', 'armband', 'armchair', 'armed', 'armful', 'armistice',
    'armor', 'armored', 'armory', 'armpit', 'army', 'aroma', 'aromatic',
    'arose', 'around', 'arouse', 'arraign', 'arraignment', 'arrange',
    'arrangement', 'array', 'arrears', 'arrest', 'arrival', 'arrive',
    'arrogance', 'arrogant', 'arrow', 'arrowroot', 'arson', 'arsonist',
    'art', 'arterial', 'artery', 'artful', 'arthritis', 'artichoke',
    'article', 'articulate', 'articulation', 'artifact', 'artifice',
    'artificial', 'artillery', 'artisan', 'artist', 'artistic',
    'artistry', 'artless', 'arts', 'artwork', 'as', 'asbestos',
    'ascend', 'ascendancy', 'ascending', 'ascent', 'ascertain',
    'ascetic', 'asceticism', 'ascribe', 'ash', 'ashamed', 'ashen',
    'ashes', 'ashore', 'ashtray', 'Asia', 'Asian', 'aside', 'asinine',
    'ask', 'askance', 'askew', 'asleep', 'asparagus', 'aspect',
    'aspen', 'asperity', 'aspersion', 'asphalt', 'asphyxiate',
    'aspirant', 'aspiration', 'aspire', 'aspirin', 'ass', 'assail',
    'assailant', 'assassin', 'assassinate', 'assassination', 'assault',
    'assemble', 'assembly', 'assent', 'assert', 'assertion', 'assertive',
    'assess', 'assessment', 'asset', 'assiduous', 'assign', 'assignment',
    'assimilate', 'assimilation', 'assist', 'assistance', 'assistant',
    'associate', 'association', 'assorted', 'assortment', 'assuage',
    'assume', 'assumption', 'assurance', 'assure', 'assured', 'asterisk',
    'astern', 'asteroid', 'asthma', 'astonish', 'astonishing',
    'astonishment', 'astound', 'astounding', 'astray', 'astride',
    'astringent', 'astrologer', 'astrology', 'astronaut', 'astronomer',
    'astronomical', 'astronomy', 'astute', 'asunder', 'asylum', 'asymmetric',
    'at', 'atavism', 'ate', 'atheism', 'atheist', 'athlete', 'athletic',
    'athletics', 'atlas', 'atmosphere', 'atmospheric', 'atom', 'atomic',
    'atone', 'atonement', 'atrocious', 'atrocity', 'atrophy', 'attach',
    'attache', 'attachment', 'attack', 'attain', 'attainable',
    'attainment', 'attempt', 'attend', 'attendance', 'attendant',
    'attention', 'attentive', 'attenuate', 'attest', 'attic', 'attire',
    'attitude', 'attorney', 'attract', 'attraction', 'attractive',
    'attractiveness', 'attribute', 'attribution', 'attrition', 'attune',
    'atypical', 'auburn', 'auction', 'auctioneer', 'audacious',
    'audacity', 'audible', 'audience', 'audio', 'audit', 'audition',
    'auditor', 'auditorium', 'augment', 'augmentation', 'augur',
    'augury', 'August', 'august', 'aunt', 'aura', 'aural', 'aurora',
    'auspices', 'auspicious', 'austere', 'austerity', 'Australia',
    'Australian', 'authentic', 'authenticate', 'authenticity', 'author',
    'authoritarian', 'authoritative', 'authority', 'authorization',
    'authorize', 'authorship', 'autism', 'autistic', 'auto', 'autobahn',
    'autobiographical', 'autobiography', 'autocracy', 'autocrat',
    'autocratic', 'autograph', 'automate', 'automatic', 'automation',
    'automaton', 'automobile', 'autonomous', 'autonomy', 'autopsy',
    'autumn', 'autumnal', 'auxiliary', 'avail', 'availability',
    'available', 'avalanche', 'avarice', 'avaricious', 'avenge',
    'avenger', 'avenue', 'average', 'averse', 'aversion', 'avert',
    'aviation', 'aviator', 'avid', 'avidity', 'avocado', 'avoid',
    'avoidance', 'avow', 'avowal', 'avowed', 'await', 'awaken', 'award',
    'aware', 'awareness', 'awash', 'away', 'awe', 'awesome', 'awful',
    'awfully', 'awhile', 'awkward', 'awkwardness', 'awning', 'awoke',
    'awoken', 'awry', 'axe', 'axiom', 'axiomatic', 'axis', 'axle',
    'azure',
  ],
};
